### ISSUE TITLE
Add mrm-maven-plugin

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#100]

**Comment by andham** [comment]
I don't see the benefit of adding lots of plugins to this parent. It is perfectly fine IMHO for each project to define additional ones.
Versions defined in the parent should be first and foremost to lock the once inplicitly defined by Maven. Then we could possibly add additional ones that we want to make sure that all projects use a specific version of.

**Comment by andham** [comment]
So I'm -1 on adding this plugin as I don't see all mojos using it (and this specific version). Those that do can specify the version used themselves.

**Comment by khmarbaise** [comment]
So based on that we have to remove:
* maven-assembly-plugin
  * no usage at all (only in parent via release).
* maven-antrun-plugin
  * No usage at all
* maven-ear-plugin
  * No usage at all
* maven-war-plugin
  * No usage at all (only within an IT for jdependency-maven-plugin; different version).
* maven-jxr-plugin
  * No usage at all (only within an IT for jdependency-maven-plugin).
* license-maven-plugin
  * Only used by cobertura-maven-plugin and jdependency-maven-plugin?
* flatten-maven-plugin
  * no usage at all.
* versions-maven-plugin
  * no usage at all. 

The following: 
* mrm-maven-plugin 
  * Used by: servicedocgen-maven-plugin, flatten-maven-plugin, jdiff-maven-plugin, exec-maven-plugin, versions-maven-plugin
  * Related to the version it should be updated in the other plugins. Currently they are overwriting it but that should be changed.

**Comment by andham** [comment]
Every plugin that is used in a build lifecycles for any of the core packages should be there. So we shouldn't remove m-ear-p or -war-p. Other than that we IMHO should only specify a version of plugins that we want to control for some reason.
Having said that I noticed, after writing my comment, that we have lots of plugins defined. And removing these will most likely break builds and make it complicated for the projects to upgrade. So removing them is probably not a good idea. Unless we want to make a major refactoring.

So I'll change my -1 to 0. Adding mrm-m-p doesn't really make it worse as we already have lots of plugins defined. But I don't think it's the right direction. But this is just my view.
