### ISSUE TITLE
Upgrade maven-site-plugin from 3.8.2 to 3.9.0

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#105]
Currently this would break build requirements. So we have to build only with 3.6.2+. My opinion is that would be fine.

**Comment by mfriedenhagen** [comment]
I think we should remove the milestone, then, @khmarbaise, do we not?

**Comment by hboutemy** [comment]
maven-site-plugin 3.9.1 is available, that fixes issues you found with 3.9.0 https://issues.apache.org/jira/browse/MSITE-863

any problem to upgrade now?
