### ISSUE TITLE
Replacing .travis with GitHub Actions

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#114]
Replace the CI tooling with GitHub actions
* Building with different JDK's (8,11,13,14)
* Building on different platforms Linux, Windows, MacOS
* Add site generation which supports release sites (https://www.mojohaus.org/mojo-parent/) as well as snapshot state (https://www.mojohaus.org/mojo-parent/snapshot/)
  * By each build on master the site will be generated. That means also the site generation is tested (like javadoc etc.).
* Add generation of release notes which is triggered by closing milestone on GitHub.

This is related to #48

**Comment by andham** [comment]
As this is a fairly big change I think it should be discussed on the mailing list. Especially as I think it makes sense to use the same CI process for all our mojos.

**Comment by jochenw** [comment]
Out of curiosity: If I understand this correctly, the GH actions are triggered by the workflow files in .github/workflows. But why is it sufficient to have them in the parent project?

**Comment by khmarbaise** [comment]
@jochenw The github actions in this project are intended for the mojo-parent only (as a first step). And no they are not inherited to sub projects etc.

**Comment by jochenw** [comment]
Thanks for the clarification. If so, could we have a mechanism in the parent, which checks, whether there are any differences between the current project, and the parent? I'd not want to see us play catch up with all our subprojects, whenever another change in these non-trivial Yaml files is required. (May be, write a Mojo, that does the check. Most likely, other projects would like to use this, too. :-)

**Comment by mfriedenhagen** [comment]
Or we have a generator project? Not sure whether we get all projects of mojohaus automatically in an easy way. And of course we need at least an exclusion list there as well.

**Comment by olamy** [comment]
done
