### ISSUE TITLE
Site rendering broken because of cobertura-maven-plugin

### ISSUE THREAD

**Issue by mfriedenhagen** [mojohaus/mojo-parent#120]
* Currently, site rendering is broken in mojo-parent-50  because of cobertura-maven-plugin
    * mojohaus/extra-enforcer-rules#99
    * https://groups.google.com/d/msg/mojohaus-dev/GTlmxA8kMmo/Ju8sZz44BAAJ
    * https://groups.google.com/d/topic/mojohaus-dev/uSZ83oGUEkQ/discussion
    * https://groups.google.com/d/topic/mojohaus-dev/8cspr6c9o7k/discussion
* Some people just want to drop it.
* Workarounds like including cobertura to a plugin's dependency in the invoker tests is at least cumbersome (and not documented properly).
* And the cobertura-maven-plugin does not work properly with JDK > 8.

**Comment by andham** [comment]
cobertura-m-p was removed by #79.

**Comment by mfriedenhagen** [comment]
Oops, sorry, should have looked harder :-) I edited the title of #77 as I did not see any reference in the title to cobertura there.
