### ISSUE TITLE
add a "docs" profile

### ISSUE THREAD

**Issue by bmarwell** [mojohaus/mojo-parent#171]
maven-javadoc-plugin is only executed on `mojo-release`.
Please give us an easy way to enable javadoc and sources without maven-gpg-plugin, maven-assembly-plugin and maven-deploy-plugin.

**Comment by slawekjaranowski** [comment]
Maybe simply always build javadoc

**Comment by slawekjaranowski** [comment]
So you want to use it, when you want build with javadoc:

```
mvn ... -P docs
```

now you can:

```
mvn ... javadoc:javadoc
```

It is a little chars more - any other difference?

**Comment by bmarwell** [comment]
Docs also include sources (the profiles I know from other projects).
But I was already open to closing this.
