### ISSUE TITLE
Manage plugin versions with properties

### ISSUE THREAD

**Issue by mfriedenhagen** [mojohaus/mojo-parent#19]
By means of this, it is much easier to update them automatically using the [versions:update-properties](http://www.mojohaus.org/versions-maven-plugin/update-properties-mojo.html)

**Comment by andham** [comment]
I don't like this. In my opinion this is the programmer's way and not the Maven way. I *always* look for the versions info in the plugin's section and get irritated when finding a property. Luckily, m2e helps me with resolving the property value but I'm not always in m2e when viewing a pom.

Also, I don't really see the versions:update-properties scenario as a real driver here. Updating the plugin versions should be a careful process for our parent pom, to ensure that good versions are used and not the always the latest.

**Comment by lennartj** [comment]
Personally, I like sensibly named properties considerably better than
version constants strewn all over the POM.
Properties are grouped together and therefore considerably more readable
than the alternative, and they can be used in a simple and visible way in
child POMs.
As a bonus option they are simpler to override in child POMs (although all
things maven can be overridden in child POMs).

Also, I am less and less sure about there being a (single) Maven way at
all.
People with different needs use different aspects of the POM as they see
fit in their projects; mostly for good reasons and where benefits outweigh
drawbacks.
For example - a POM used as a BOM (i.e. a POM used i *import* scope) had
better use properties for all its declared dependencies to permit users of
the BOM to synchronize versions with dependencies in the BOM.

Hence, I would rather consider the use of version properties in a parent
POM (or BOM) better practice than the opposite.
This is a different view - but possibly with the same direction - as what I
perceive Mirko's properties in the POM to be.


2015-07-23 8:51 GMT+02:00 Anders Hammar <notifications@github.com>:

> I don't like this. In my opinion this is the programmer's way and not the
> Maven way. I *always* look for the versions info in the plugin's section
> and get irritated when finding a property. Luckily, m2e helps me with
> resolving the property value but I'm not always in m2e when viewing a pom.
>
> Also, I don't really see the versions:update-properties scenario as a real
> driver here. Updating the plugin versions should be a careful process for
> our parent pom, to ensure that good versions are used and not the always
> the latest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojohaus/mojo-parent/issues/19#issuecomment-123998218>
> .
>



-- 

--
+==============================+
| Bästa hälsningar,
| [sw. "Best regards"]
|
| Lennart Jörelid
| EAI Architect & Integrator
|
| jGuru Europe AB
| Mölnlycke - Kista
|
| Email: lj@jguru.se
| URL:   www.jguru.se
| Phone
| (skype):    jgurueurope
| (intl):     +46 708 507 603
| (domestic): 0708 - 507 603
+==============================+

**Comment by mfriedenhagen** [comment]
Some of the discussion is happening on the [mailing list](https://groups.google.com/forum/#!topic/mojohaus-dev/xxWBUkGe3rc)

**Comment by mfriedenhagen** [comment]
As discussed on the mailing list, this found no majority, so I just close this.
