### ISSUE TITLE
update ci information

### ISSUE THREAD

**Issue by hboutemy** [mojohaus/mojo-parent#2]
I don't know what's the target, but at least this issue will help us track the issue :)
(and learn on simple things how to use the new github issues system)

**Comment by wguttmn** [comment]
As I had to migrate another project from Codehaus to github recently (Castor, that is), I settled on Travis for CI and configured the relevant POM section as follows - after setting up Castor on Travis. 

```
    <ciManagement>
        <system>Travis CI</system>
        <url>https://github.com/castor-data-binding/castor</url>
    </ciManagement>
```

No idea whether Travis is the way to go forward.

**Comment by mfriedenhagen** [comment]
BTW. the system name seems to be travis according to: [CimReport](http://svn.apache.org/viewvc/maven/plugins/tags/maven-project-info-reports-plugin-2.8/src/main/java/org/apache/maven/report/projectinfo/CimReport.java?view=markup) line 161
