### ISSUE TITLE
Name of release 65.0.1 not in sync with tag

### ISSUE THREAD

**Issue by pzygielo** [mojohaus/mojo-parent#210]
![parent](https://user-images.githubusercontent.com/11896137/147067092-4b6c7f38-e172-4a85-9500-9d25da509f18.png)

**Comment by stefanseifert** [comment]
it seems both the github release and the tag was put there accidentally - on maven central version 65 is the latest release available (from Nov '21).
@slachiewicz can you check if the tag and github release should be removed?

**Comment by stefanseifert** [comment]
i've provided a PR #214 which should fix the issue in the release drafter config
i also provided a configuration that matches the single version number scheme that is in place for this parent POM

it's still required to manually clean up the invalid release and tag 65.0.1/65.1.0

**Comment by slachiewicz** [comment]
i've updated releases - hope now it looks ok

**Comment by stefanseifert** [comment]
lgtm, thanks!

the wrong tag is still present, though: https://github.com/mojohaus/mojo-parent/tree/mojo-parent-65.1.0
