### ISSUE TITLE
use variable for github project

### ISSUE THREAD

**Issue by hohwille** [mojohaus/mojo-parent#25]
IMHO the idea of mojo-parent is to define the common sense for mojohaus projects.
Hence, I would suggest to define a property like `mojohaus.project.name` that defaults to `mojo-parent`. Then instead of hard-coding `mojo-parent` in `issueManagement`, `distributionManagement`, `scm`, etc. just use the variable.
Then the mojohaus projects can simply override the `mojohaus.project.name` and that's it.
I forgot to override `issueManagement` in `servicedocgen-maven-plugin` and hence you can see the github issue report for `mojo-parent` on my maven site.
The property could avoid a lot of redundancy.

**Comment by hboutemy** [comment]
+1 great idea

**Comment by hboutemy** [comment]
distributionManagement and scm won't work because of inheritance: see https://issues.apache.org/jira/browse/MNG-4508
what we can do is to use variables, but child poms still will require copy/paste to avoid extra-artifactId at end

do you see anything else to improve before closing this issue?
