### ISSUE TITLE
Why is it not possible to set dirmode on individual mappings?

### ISSUE THREAD

**Issue by sc1478** [mojohaus/mojo-parent#27]
I would like to build an rpm where one directory has a different dirmode than the default.  This option is not available, whereas <filemode>, <username>, and <groupname> are available on the mapping level.
Why the difference?

By the way, this issue has been floating around since 2010:

http://mojo.10943.n7.nabble.com/rpm-maven-plugin-is-there-any-way-to-specify-the-dirmode-other-than-the-defaultDirmode-attribute-td37839.html

**Comment by khmarbaise** [comment]
First i would suggest to use [this area to put issues in](https://github.com/mojohaus/rpm-maven-plugin)...and not the mojohaus parent.

**Comment by sc1478** [comment]
Sorry, reopened it there.  closing this one
