### ISSUE TITLE
Move codecoverage plugins to separate profile

### ISSUE THREAD

**Issue by rfscholte** [mojohaus/mojo-parent#28]
While trying to do some jigsaw related improvements I noticed that with the current parent it will be impossible to build a project with JDK9. The cause is the cobertura-plugin. It is part of the default build AND it depends on tools.jar, which doesn't exist anymore in JDK9.
By moving it to a codecoverage profile we have the option to enable or disable it when we want. It won't have any effect on the resulting artifact, only on the quality statistics.

**Comment by khmarbaise** [comment]
Would it be a good idea to change to JaCoCo ? I'm not 100% sure if JaCoCo supports JDK9 ?

**Comment by rfscholte** [comment]
Based on what I've seen on the jigsaw mailinglist there are still some issues with the javaagent. But I agree that jacoco is a better approach. One way or another, it is still valid to control the codecoverage with a profile.

**Comment by khmarbaise** [comment]
VOTE for profile....

**Comment by rfscholte** [comment]
I'm not going to start a vote for it, see the commit: effectively there's no change to the current behavior and it is a requirement to be able to disable the plugin without its dependency resolution.
