### ISSUE TITLE
Upgrade to Maven 3+ only parent

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#45]
Removing the prerequisites and using maven-enforcer-plugin to check the minimum version of Maven to use.

**Comment by khmarbaise** [comment]
We should also bump the version to 50 so we have a chance to make a bug fix if need.

**Comment by andham** [comment]
The message in the enforcer rule should be changed/removed. See comment in commit.

**Comment by khmarbaise** [comment]
Sure you are right...
