### ISSUE TITLE
make requireEncoding validate encoding rather than detect encoding by ICU4J

### ISSUE THREAD

**Issue by wilx** [mojohaus/mojo-parent#50]
It seems that the `requireEncoding` rule is detecting ISO-8859-1 where my IDE happily detects UTF-8. It seems to me that instead of detecting encoding the rule should try to parse files with desired encoding and signal decoding failures instead.

**Comment by andham** [comment]
I believe this is for the Extra Enforcer Rules. Each projekt has its own issue tracker so you need to file it there:
https://www.mojohaus.org/extra-enforcer-rules/issue-tracking.html
