### ISSUE TITLE
2.5 breaks dependent projects with independent version numbers

### ISSUE THREAD

**Issue by efenderbosch** [mojohaus/mojo-parent#53]
Previous versions would simply substitute the version text, for example 1.2.047 -> 1.2.048.

Version 2.5, however changes this behavior to simply use ${project.version}. This breaks projects that use a reactor as a parent that have independent version numbers.

For example:
If I have a project version 1.3.002 that has a parent of version 1.2.047, then it keeps looking for all my dependencies w/ version 1.3.002 instead of 1.2.047.

We have a reactor that's used as a parent for a dozen or more projects, each with their own versioning and release schedule. For now, we've reverted to using 2.4.

**Comment by khmarbaise** [comment]
This is is intended for versions -maven-plugin if I correctly understand...This project is the mojo-parent...please add this issue to https://github.com/mojohaus/versions-maven-plugin/issues
