### ISSUE TITLE
rulesUri property://

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [mojohaus/mojo-parent#56]
in many cases there is a need for self-contained `pom.xml`

please add support for new `rulesUri` scheme `property://`
```
<!-- project level -->

<properties>
   <custom.ruleset>
<![CDATA[
       <ruleset comparisonMethod="maven">
       </ruleset>   
]]>
   </custom.ruleset>
</properties>

<!-- plugin level -->

   <configuration>
      <rulesUri>property://custom.ruleset</rulesUri>
   </configuration>
```

**Comment by khmarbaise** [comment]
Can you please move this request to here: https://github.com/mojohaus/versions-maven-plugin/issues

**Comment by Andrei-Pozolotin** [comment]
moved to: https://github.com/mojohaus/versions-maven-plugin/issues/228
