### ISSUE TITLE
generateEpisode in schemagen  not working

### ISSUE THREAD

**Issue by vagostep** [mojohaus/mojo-parent#60]
when i set the <generateEpisode>false</generateEpisode> is still create the META-INF/ folder

using 
`<groupId>org.codehaus.mojo</groupId>
<artifactId>jaxb2-maven-plugin</artifactId>
<version>2.2</version>`

**Comment by andham** [comment]
You need to file this ticker for the jaxb2-maven-plugin:
https://github.com/mojohaus/jaxb2-maven-plugin/issues
