### ISSUE TITLE
<missingFile> not working on aggregate-add-third-party

### ISSUE THREAD

**Issue by blurio** [mojohaus/mojo-parent#63]
Hello,

i have a multi module project and want to use the aggregate-add-third-party goal.
I believe that i should use the <missingFile> tag with a path to my missing file, correct?

So i'm using something like this 
`<missingFile>E:/workspace/project/THIRD-PARTY.properties</missingFile>`

The plugin does not read anything at that location and in fact maven reports this warning in the console
`[WARNING] You should use *missingFile* parameter instead of deprecated *aggregateMissingLicensesFile*.`

I am not using aggregateMissingLicensesFile in my configuration, it still thinks i do. 
I can also only resolve unknown licenses by copy and pasting a missing file into every single module in my project that has an unknown license. 

Is this a bug or am i doing something wrong?

Regards,
K

**Comment by TorstenKruse** [comment]
Hey @blurio your issue is in the wrong project. Look like you followed the same broken link as I did.

**Comment by andham** [comment]
Not sure what mojo this is for, but every mojo/plugin has its own issue tracker. You need to find the right one and file the issue there.
