### ISSUE TITLE
Upgrade maven plugins

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#65]
Upgrade Maven Plugins:
     * maven-javadoc-plugin 3.0.1
     * maven-clean-plugin 3.1.0
     * maven-compiler-plugin 3.7.0
     * maven-dependency-plugin 3.1.1 (superseded by #86)
     * maven-help-plugin 3.1.0 (supersede by #87)
     * maven-invoker-plugin 3.1.0 (superseded by #88)
     * maven-jar-plugin 3.1.0
     * maven-war-plugin 3.2.2
     * maven-ear-plugin 3.0.1
     * maven-plugin-plugin 3.5.2
     * maven-release-plugi 2.5.3
     * maven-resources-plugin 3.1.0
     * maven-scm-publish-plugin 3.0.0
     * maven-site-plugin 3.7.1
     * maven-surefire/failsafe 2.22.0
     * flatten-maven-plugin 1.0.0 (superseded by #89)
    Upgrade dependencies:
     * maven-plugin-annotations 3.5.2

**Comment by andham** [comment]
A few of these plugins/deps have been upgraded independently.

**Comment by andham** [comment]
@khmarbaise can vi close this as upgrades are handled in other separate PRs?

**Comment by khmarbaise** [comment]
Ups ..oversight that you have created a pr.

**Comment by khmarbaise** [comment]
can we chat here: is faster than via issue .. https://gitter.im/mojohaus/mojo-parent
