### ISSUE TITLE
This is not an issue but a question.

### ISSUE THREAD

**Issue by A-AFTAHI** [mojohaus/mojo-parent#67]
i'm newbie with gradle and dependencies, and i'm working on a project for mobile applications developped on Java, and want to know if there is a new version for all existent libraries. it like creating a project which depends on all maven libraries and then use this method to check if there is new versions.
if someone can help me how can i make this happen.

**Comment by andham** [comment]
Please ask questions on the mailing list: http://www.mojohaus.org/mail-lists.html
