### ISSUE TITLE
maven-pmd-plugin configuration contains reference to broken mojo_rules.xml

### ISSUE THREAD

**Issue by wemu** [mojohaus/mojo-parent#7]
hello

the maven-pmd-plugin contains

    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-pmd-plugin</artifactId>
      <version>3.4</version>
      <configuration>
        <targetJdk>${mojo.java.target}</targetJdk>
        <rulesets>
         <ruleset>http://svn.codehaus.org/mojo/tags/mojo-parent-34/src/main/config/pmd/mojo_rules.xml</ruleset>
        </rulesets>

This breaks generating the maven site for (most?) plugins. Currently at least the rpm-maven-plugin site is affected.

Not sure how the link is replaced during a release. I guess it should look similar to:
    https://raw.githubusercontent.com/mojohaus/mojo-parent/mojo-parent-34/src/main/config/pmd/mojo_rules.xml

**Comment by mfriedenhagen** [comment]
Someone already removed the `rulesets` completely, so at least if was working again, see #8 as well.
