### ISSUE TITLE
document of Usage has  a spelling mistake

### ISSUE THREAD

**Issue by nurhier** [mojohaus/mojo-parent#70]
In the document of usage has a spelling mistake, the chapter path is ['MojoHaus /  MojoHaus Parent /  Build Number Maven Plugin /  Usage / **Create Build Metadata**](https://www.mojohaus.org/buildnumber-maven-plugin/usage.html)'. The value 'generate-ressources' of label 'phase' is error.

**Comment by TobiX** [comment]
This should probably be reported against the [buildnumber-maven-plugin](https://github.com/mojohaus/buildnumber-maven-plugin)

**Comment by andham** [comment]
Right, the buildnumber-maven-plugin has its own issue tracker:
https://www.mojohaus.org/buildnumber-maven-plugin/issue-tracking.html
