### ISSUE TITLE
there is problems when i use 2.7

### ISSUE THREAD

**Issue by silloy** [mojohaus/mojo-parent#71]
when i use 2.7, I get the problem
```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /Users/xxx/.m2/repository/org/codehaus/mojo/versions-maven-plugin/2.7/versions-maven-plugin-2.7.pom: entity reference name can not contain character =' (position: START_TAG seen ...SLOG_URL = \'http://slog.wiwide.com/p.gif?slog=portal_success&time=... @9:80)  @ line 9, column 80
```

so, I see the source code, there is some problem here.
![image](https://user-images.githubusercontent.com/12909107/59157874-0bb3fe00-8ae5-11e9-9424-fec5572add18.png)

And I change to 2.6. it not appear, finally. I use 2.6

**Comment by TobiX** [comment]
You seem to be behind a proxy which replaces downloads from maven central with HTML files.

Anyways, this should probably be reported against the [versions-maven-plugin](https://github.com/mojohaus/versions-maven-plugin)

**Comment by silloy** [comment]
I downloaded the package from https://mvnrepository.com/artifact/org.codehaus.mojo/versions-maven-plugin/2.7.   theoretically, when i downloaded the package, I use `mvn versions` there is nothing with the web. I hope the bug can be fixed next version sincerely!

**Comment by andham** [comment]
If this is an issue, it needs to be filed with the versions-maven-plugin. It has its own git repo and issue tracker:
https://www.mojohaus.org/versions-maven-plugin/issue-tracking.html
