### ISSUE TITLE
update-parent work with maven-3.6.1 but not maven-3.6.3

### ISSUE THREAD

**Issue by eisig** [mojohaus/mojo-parent#75]
versions-maven-plugin:2.7

my command is 
`
 mvn versions:update-parent -B -U -DallowSnapshots=true -Dmaven.version.rules=https://xxx/version_rules/raw/master/release_versions.xml '-DparentVersion=[5.5,5.6)'
`

release_versions.xml:
I want to use version contains "RELEASE"
```
<ruleset comparisonMethod="maven"
         xmlns="http://mojo.codehaus.org/versions-maven-plugin/rule/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://mojo.codehaus.org/versions-maven-plugin/rule/2.0.0 http://mojo.codehaus.org/versions-maven-plugin/xsd/rule-2.0.0.xsd">
  <rules>

    <rule groupId="com.mycom" comparisonMethod="mercury">
      <ignoreVersions>
        <ignoreVersion type="regex">^((?!RELEASE).)+$</ignoreVersion>
      </ignoreVersions>
    </rule>
    
  </rules>
</ruleset>
```

using maven 3.6.1 
Updating parent from 5.5.0-SNAPSHOT to 5.5.0.RELEASE-SNAPSHOT

using 3.6.3:
[WARNING] Not updating version: could not resolve any versions

**Comment by andham** [comment]
This issue should be filed with the versions-m-p which has its own git repo and issue tracker:
https://www.mojohaus.org/versions-maven-plugin/issue-tracking.html
