### ISSUE TITLE
Fix Java 11 build

### ISSUE THREAD

**Issue by andham** [mojohaus/mojo-parent#77]
The project is not buildable with Java 11. It fails due to the cobertura-m-p, which can be seen in the Travis builds.
Also see #39 and #59 which are about issues with cobertura.
The issue about java 11 filed for cobertura-m-p: https://github.com/mojohaus/cobertura-maven-plugin/issues/43

**Comment by andham** [comment]
As cobertura-m-p isn't Java 11 compatible, what should we do? Should we fix it, or should we switch to some other code coverage tool? If we should switch, to what?
Or, should we just remove the code coverage report all together? I think our mojos mainly have tests via the invoker-m-p so that coverage will not be included in the report anyways as those tests are not instrumented.

**Comment by hboutemy** [comment]
+1 to remove

**Comment by andham** [comment]
It looks like Cobertura isn't Java 11 compatible, see https://github.com/cobertura/cobertura/issues/381. So fixing cobertura-m-p to be Java 11 compatible isn't possible.

**Comment by andham** [comment]
Discussion on dev mailing list: https://groups.google.com/forum/#!topic/mojohaus-dev/8cspr6c9o7k

Conclusion: I nice thing to have, but need to switch to e.g. JaCoCo. Most likely we need to instrument the invoker-m-p driven tests as well as most mojo test are there.

But for now we settle on removing coberture-m-p. Something else could be added in the future if needed.
