### ISSUE TITLE
Removed properties which define versions of plugins

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#91]
We should remove the following properties from the mojo-parent:
* maven-javadoc-plugin.version
* maven-changes-plugin.version
* maven-checkstyle-plugin.version
* maven-project-info-reports-plugin.version

**Comment by mfriedenhagen** [comment]
* I am still not convinced that properties are that evil. 
* Extracting versions in properties is done in e.g. spring-boot for almost every dependency.
* And when using properties the versions-maven-plugin is able to update plugin versions as well, which comes quite handy.

**Comment by olamy** [comment]
I do not agree to see this as evil
